-- ==========================================
-- Queue Cure Database Schema & Configuration
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. Create the queue table
CREATE TABLE IF NOT EXISTS queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_name TEXT NOT NULL,
  token_number INTEGER GENERATED BY DEFAULT AS IDENTITY,
  status TEXT CHECK (status IN ('waiting', 'in-consultation', 'completed')) DEFAULT 'waiting',
  called_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the settings table
CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  current_serving_token INTEGER DEFAULT 0,
  initial_avg_consultation_time INTEGER DEFAULT 15,
  reset_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Insert initial settings row if it doesn't exist
INSERT INTO settings (id, current_serving_token, initial_avg_consultation_time, reset_at) 
VALUES (1, 0, 15, NOW())
ON CONFLICT (id) DO NOTHING;

-- 4. Enable Row Level Security (RLS) for tables
ALTER TABLE queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies to allow anonymous public operations (for development simplicity)
CREATE POLICY "Allow public operations on queue" ON queue FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public operations on settings" ON settings FOR ALL USING (true) WITH CHECK (true);

-- 6. Enable Realtime Replication for the tables
ALTER PUBLICATION supabase_realtime ADD TABLE queue;
ALTER PUBLICATION supabase_realtime ADD TABLE settings;

-- 7. Create the Stored Procedure (RPC) to call the next patient atomically
CREATE OR REPLACE FUNCTION call_next_patient() RETURNS void AS $$
DECLARE
    next_token INTEGER;
BEGIN
    -- Find the next waiting patient, locking the row for transaction safety
    SELECT token_number INTO next_token 
    FROM queue 
    WHERE status = 'waiting' 
    ORDER BY token_number ASC 
    LIMIT 1 
    FOR UPDATE;
    
    IF next_token IS NOT NULL THEN
        -- Mark previous in-consultation as completed
        UPDATE queue SET status = 'completed' WHERE status = 'in-consultation';
        
        -- Mark next as in-consultation and record called_at
        UPDATE queue SET status = 'in-consultation', called_at = NOW() WHERE token_number = next_token;
        
        -- Update current serving token in settings
        UPDATE settings SET current_serving_token = next_token WHERE id = 1;
    END IF;
END;
$$ LANGUAGE plpgsql;
